schedules:
- cron: "0 22 * * *"
  displayName: Master nightly build
  branches:
    include:
    - master
  always: true
jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'
  steps:
  - script: pip install --requirement continuous-integration\python-requirements\build.txt
    displayName: 'Install python requirements'
  - script: python continuous-integration\windows\build.py --root %CD%
    displayName: 'Build'
    env: { 'Zivid_DIR': 'C:\Program Files\Zivid\CMake\Zivid', 'CXX': 'cl.exe', 'CC': 'cl.exe'}
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      ArchLinux:
        os: 'archlinux/base'
        command: './lint.sh'
      Ubuntu2004:
        os: 'ubuntu:20.04'
        command: './test.sh'  
      Ubuntu1804:
        os: 'ubuntu:18.04'
        command: './test.sh'
      Ubuntu1604:
        os: 'ubuntu:16.04'
        command: './test.sh'
      Fedora30:
        os: 'fedora:30'
        command: './test.sh'
  steps:
  - script: docker run
              --volume $PWD:/host
              --workdir /host/continuous-integration/linux
              --env "PYTHONDONTWRITEBYTECODE=1"
              $(os)
              bash -c "./setup.sh && $(command)"
    displayName: 'Build and test'
